version: '3.9'

services:

  jsapp:
    container_name: jsapp
    image: wendel/jsapp
    build:
      context: js
    ports:
      - "3000:3000"
    environment:
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=ra04ra
      - PGHOST=db
      - EXTERNALHOST=3000
    depends_on:
      - db

  pythonapp:
    container_name: pythonapp
    image: wendel/pythonapp
    build:
      context: python
    ports:
      - "80:80"
    environment:
      - DB_URI=postgresql://postgres:ra04ra@db:5432/postgres
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ra04ra
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}